resource:
  shared_resource:
    # cloud formation stack
    resources_cf_stack_name: "BanditsSharedResourceStackSG"
    # Dynamo table for status of an experiment
    experiment_db:
      table_name: "BanditsExperimentTable"
    # Dynamo table for status of all models trained
    model_db:
      table_name: "BanditsModelTable"
    # Dynamo table for status of all joining job for reward ingestion
    join_db:
      table_name: "BanditsJoinTable"
    iam_role:
      role_name: "BanditsIAMRole"
  private_resource:
    hosting_fleet:
      instance_type: "ml.t2.medium"
      instance_count: 1
    training_fleet:
      instance_type: "ml.c5.4xlarge"
    evaluation_fleet:
      instance_type: "ml.c5.4xlarge"
# Contextual Bandit container
# The new ADF image is only present in us-east-1 and us-west-2 for now.
image: "462105765813.dkr.ecr.{AWS_REGION}.amazonaws.com/sagemaker-rl-vw-container:adf"
# Algorithm parameters
algor:
  algorithms_parameters:
    exploration_policy: "egreedy" # supports "egreedy", "bag", "cover"
    epsilon: 0 # used if egreedy is the exploration policy
    num_policies: 3 # used if bag or cover is the exploration policy
    arm_features: false # true if each arm/action is represented by a feature vector. Useful with dynamic no. of actions
    num_arms: 7 # ignored when "arm_features" is set to true
    cfa_type: "dr" # supports "dr", "ips"
# use local mode?
local_mode: true
# if true, use the same endpoint with updated model
soft_deployment: true
 
